name: bestwaytoproceedanalyze
description: "A new Flutter project."
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: '>=3.4.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  bestwaytoproceed:
    git:
      url: https://github.com/riadhrahma/bestwaytoproceedcore.git
      ref: dev
  firebase_crud:
    git:
      url: https://github.com/riadhrahma/firebase_crud.git
      ref: dev

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
